"""empty message

Revision ID: 0dfb8a0c9162
Revises: a30eaa14f2bd
Create Date: 2025-02-01 10:33:35.884243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dfb8a0c9162'
down_revision = 'a30eaa14f2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('male', 'female', name='gender'),
               existing_nullable=True)

    # ### end Alembic commands ###
