"""empty message

Revision ID: 5941c4261d17
Revises: f2beb79215bd
Create Date: 2025-02-01 11:51:24.903511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5941c4261d17'
down_revision = 'f2beb79215bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('male', 'female', 'hermaphrodite', 'n/a', name='gender'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female', 'hermaphrodite', 'n/a', name='gender'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
