"""empty message

Revision ID: 90d60c3cd775
Revises: 0dfb8a0c9162
Create Date: 2025-02-01 10:51:51.548877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d60c3cd775'
down_revision = '0dfb8a0c9162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
