"""empty message

Revision ID: f2beb79215bd
Revises: e23ad3205f89
Create Date: 2025-02-01 11:43:31.230057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2beb79215bd'
down_revision = 'e23ad3205f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('mass',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
